######################################################################
# Automatically generated by qmake (2.01a) sob. kwi 8 12:02:43 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    tcp_server/tcp_server.h
SOURCES += main.cpp  \
    tcp_server/tcp_server.cpp
